spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/dev/user/**
          filters:
            - RewritePath=/api/dev/user/(?<segment>.*),/$\{segment}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/dev/project/**
          filters:
            - RewritePath=/api/dev/project/(?<segment>.*),/$\{segment}
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/dev/task/**
          filters:
            - RewritePath=/api/dev/task/(?<segment>.*),/$\{segment}
  sleuth:
    sampler:
      probability: 1
    zipkin:
      base-url: http://host.docker.internal:9411

server:
  port: 8762

eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
  context-path: http://localhost:${server.port}/actuator


info:
  application:
    name: ${spring.application.name}
    description: Ticketing Application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
